### PR TITLE
Bugfix: Added return - because Method doSetValue throws always

### PR DESCRIPTION
**Pull request by ShawnKleese**
Bugfix: Added return - because Method doSetValue throws always IllegalArgumentException

### CODE REVIEW

**Comment by tomsontom** [comment]
@ShawnKleese the change itself looks good but before merging and attributing to you. I need to ask you to sign the Eclipse ECA

**Comment by ShawnKleese** [comment]
Hey Tom,
thank you for your fast response. I've checked the Eclipse ECA.

**Comment by tomsontom** [comment]
sorry did not read the error message appropriately - if you click the link you see that your commit message needs to contain a last line `Signed-off-by: shawn.kleese@....`.

**Comment by tomsontom** [comment]
hm - the problem now is that there's are 2 commits:
* one without the required Signed-off-by
* one with the required Signed-off-by
You could have simply amended the initial commit and force push it :-( Sorry to be so painful

**Pull request merged**
