### PR TITLE
issue #287:preferences spy added

### PR DESCRIPTION
**Pull request by lauritziu**
This PR brings the preferences spy.

- it can track changed preferences (toggle the "trace option" and you'll see it)

### CODE REVIEW

**Comment by tomsontom** [comment]
As this contribution is above 1,000 loc I need to run it throught the IP team

**Comment by tomsontom** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19638

**Comment by lauritziu** [comment]
We need to close the company Github repo. I would host the changes in my local Github repo. Is there a way to migrate the open PR's regarding the Spies? Or any chance to merge that stuff in the next couple of days?

**Comment by tomsontom** [comment]
I can't give a timeline until when i get a +1/-1 from the IP team

**Comment by tomsontom** [comment]
uh oh - just got approval for the first patch!

**Pull request merged**
