### PR TITLE
Issue #287:context spy added

### PR DESCRIPTION
**Pull request by lauritziu**
This adds the context spy.

### CODE REVIEW

**Comment by tomsontom** [comment]
As this contribution is above 1,000 loc I need to run it throught the IP team

**Comment by tomsontom** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19640

**Comment by lauritziu** [comment]
Ok, but most code is taken from the original Eclipse tools project. It doesn't matter? Can I do anything with that?

**Comment by tomsontom** [comment]
no need for you to do anything!

**Pull request merged**
