### PR TITLE
Resolved potential deadlock in FxClassLoader

### PR DESCRIPTION
**Pull request by friedrichpit**
refs #429 
- removed `synchronized` from `postFindClass`
- field `reentrance` ist ThreadLocal

### CODE REVIEW

**Comment by tomsontom** [comment]
looks good but it looks like you've not yet signed the ECA?!

**Comment by tomsontom** [comment]
I think the problems are the first commits don't have the footer - so you'd have to squash the commits into one with the correct footer or if it is simpler create a new PR with just the correct commit ;-)

**Comment by friedrichpit** [comment]
First commits don't have the required footer. Closing. Drafting new pull request.

**Comment by qtran** [comment]
I have a question concerning this patch. FXClassloader is not only used in the Main Thread. We are speeding up the loading of FXML etc in a background task/thread pool. My concern is that this patch will cause memory leaks, see https://techblog.bozho.net/threadlocal-variables-and-thread-pools-it-can-go-wrong/

**Pull request closed without merging**
