### PR TITLE
Fixes #287: migrated E4 Spy tools framework

### LINKED ISSUE #287: Migrate the SWT E4 Spy Tools to JavaFX
To support the development of a E4 application some very useful tools exist helping to investigate the current state of a running E4 application. To get an impression of the tools see the following video.

The following tools exists:

Model Spy (investigate the current application model)
Context Spy (provides a deep insight into the context hierarchy with search support)
Preferences Spy (shows available preferences and changes to it)
Event Spy (observes all the Eclipse events fired and allows to filter the events)
These tools are great but they are all written in SWT and therefore not easily usable in a JavaFx Eclipse application.

It would be great to migrate the tools to JavaFX and provide them with the efxclipse tooling.

### PR DESCRIPTION
**Pull request by lauritziu**
This is the first pull request regarding issue #287 . 

There are three more pull requests for each migrated spy. There are the following to be expected:
* Context Spy
* Event Spy
* Preferences Spy

This request here provides the framework which is providing a new menu entry in the main toolbar and have a dynamic menu contribution which searches for available spies.

All the modules coming regarding this issue are build by maven and using the efx target platform feature artifact. It is not integrated into the `releng` modules, because we are not sure what is wanted.

### CODE REVIEW

**Comment by tomsontom** [comment]
It looks like not all people have signed the contributor agreement?

**Comment by tomsontom** [comment]
I'm fine with having this not part of the default releng build until we've refactored the complete build process to use the pure maven story.

I'll review the sources later but this looks like great work @lauritziu @ogssotze !

**Comment by lauritziu** [comment]
You are right we have to change the author of the commits. I have signed the agreement. I'll fix this during the day. Other stuff will follow today as well.

**Comment by lauritziu** [comment]
One problem I expect is a missing defined maven repository. We have our own settings.xml we are using for each project but this one is not committed.

**Comment by lauritziu** [comment]
I change the author of the last commit to me. I have signed the contributor agreement. What's wrong?

**Comment by tomsontom** [comment]
What is displayed in the details link?

**Comment by lauritziu** [comment]
Link is: 
https://accounts.eclipse.org/legal/eca/validation/275

**Comment by lauritziu** [comment]
At the details page (when I'm logged in) is the following:
`Thomas Fahrmeyer (lauritziu_ii@****.de) did not include the "Signed-off-by footer" which is required for all commits made by a contributor.`

There was an option to revalidate. I did it. Don't know what the "signed-off-by footer" means.

**Comment by tomsontom** [comment]
see https://wiki.eclipse.org/Development_Resources/Contributing_via_Git the last line in your commit needs to contain it

**Comment by lauritziu** [comment]
May be the problem is my setup. In my Github account (for that I have signed the ECA) I have an organisation. Under behalf of the organisation account that stuff was committed. 

I have re-committed the stuff from the pull requeset with git option `-s` which generates the signed-off-by header in the commit message. But this is different mail than my original Github account. Should I try to change the email address in the signed-header to match my github email address?

I'll just try it :)

**Comment by lauritziu** [comment]
Ok, that fixed it.

**Comment by lauritziu** [comment]
Should the copyright be the same as in your code? Does it need to be Eclipse Public License v1.0?

**Comment by tomsontom** [comment]
* yes the project is still Eclipse Public License v1.0 - we plan to move to 2.0 in the near future
* if the file is copied from upstream you need to keep the copyright
* if the file is new - then yes add a copyright like in all other files but exchange BestSolution.at and my name to yours

**Comment by lauritziu** [comment]
Got it :) Thanks for the support.

**Comment by lauritziu** [comment]
Any chance to get that merged? ;)

**Pull request merged**
