### PR TITLE
#405 IllegalAccessError on simple application

### PR DESCRIPTION
**Pull request by ShawnKleese**

### CODE REVIEW

**Comment by tomsontom** [comment]
i highly doubt that this setting fixes the problems I also sometimes saw when running a simple application, there must be another reason why the export is not respected or do can you give a reason why the above line should fix something?

**Comment by ShawnKleese** [comment]
Ok... yes... After some investigating i doubt it self :-/ I had some Problems to execute my Code...


I think this Problem is caused by Java bytecode version is 8 and it should be Java 11.

When it is planed to go for Java 11? I have heard that eclipse Ide sets Java 11 in the next release(2020-09) as minimal JRE Version 11 as PreReq.

**Comment by tomsontom** [comment]
If i would have to guess it could be a threading issue?

**Comment by ShawnKleese** [comment]
Here is the Stack. It is executed on the JavaFX Application Thread. I think it is good. Or what you're expecting?

`de.my.rcp.product [Eclipse Application]	
	org.eclipse.equinox.launcher.Main at localhost:65485	
		Thread [main] (Running)	
		Thread [Active Thread: Equinox Container: 2ac4cdd7-bd62-422b-8e98-e32e717db0e2] (Running)	
		Daemon Thread [Framework Event Dispatcher: Equinox Container: 2ac4cdd7-bd62-422b-8e98-e32e717db0e2] (Running)	
		Daemon Thread [Start Level: Equinox Container: 2ac4cdd7-bd62-422b-8e98-e32e717db0e2] (Running)	
		Daemon Thread [Refresh Thread: Equinox Container: 2ac4cdd7-bd62-422b-8e98-e32e717db0e2] (Running)	
		Daemon Thread [Bundle File Closer] (Running)	
		Daemon Thread [SCR Component Actor] (Running)	
		Thread [Gogo shell] (Running)	
		Thread [app thread - org.eclipse.fx.ui.workbench.fx.application.0] (Running)	
		Thread [JavaFX-Launcher] (Running)	
		Daemon Thread [QuantumRenderer-0] (Running)	
		Daemon Thread [InvokeLaterDispatcher] (Running)	
		Thread [JavaFX Application Thread] (Suspended)	
			DefaultJFXApp.setProductApplicationName() line: 85	
			DefaultJFXApp.<init>(E4Application) line: 54	
			DefaultJFXApp.<init>() line: 39	
			NativeConstructorAccessorImpl.newInstance0(Constructor<?>, Object[]) line: not available [native method]	
			NativeConstructorAccessorImpl.newInstance(Object[]) line: 62	
			DelegatingConstructorAccessorImpl.newInstance(Object[]) line: 45	
			Constructor<T>.newInstance(Object...) line: 490	
			LauncherImpl.lambda$launchApplication1$8(Class, AtomicReference, String[]) line: 802	
			49162038.run() line: not available	
			PlatformImpl.lambda$runAndWait$12(Runnable, CountDownLatch) line: 455	
			468381491.run() line: not available	
			PlatformImpl.lambda$runLater$10(Runnable) line: 428	
			1031499101.run() line: not available	
			AccessController.doPrivileged(PrivilegedAction<T>, AccessControlContext) line: not available [native method]	
			PlatformImpl.lambda$runLater$11(Runnable, AccessControlContext) line: 427	
			401110568.run() line: not available	
			InvokeLaterDispatcher$Future.run() line: 96	
			WinApplication._runLoop(Runnable) line: not available [native method]	
			WinApplication.lambda$runLoop$3(int, Runnable) line: 174	
			1032320556.run() line: not available	
			Thread.run() line: 834	
		Daemon Thread [Thread-4] (Running)	
	###\openjdk-11.0.2\bin\javaw.exe (23.06.2020, 18:00:16)	`

**Comment by tomsontom** [comment]
Can you reproduce this constantly? To me this happened only from time to time!

**Comment by ShawnKleese** [comment]
yes, on every Application Start

**Comment by tomsontom** [comment]
Ok that's good! So we might have a chance to sort out why that happens because as I said to me this happens not all time and so diagnosing that is very hard. Let's discuss the details in the open ticket

**Comment by tomsontom** [comment]
so I think i fixed the with problem - https://github.com/eclipse-efx/efxclipse-rt/commit/277e3a703c666794f813f73bb228dc30490063cd

**Comment by Apetree100122** [comment]
de.my.rcp.product [
Eclipse Application]
	 org.eclipse.equinox.launcher.Main at localhost:65485
	 Thread [main] (Running)	 
Thread [Active Thread: Equinox Container: 
2ac4cdd7-bd62-422b-8e98-e32e717db0e2] (Running)	 
Daemon Thread 
[Framework Event Dispatcher: Equinox Container: 
2ac4cdd7-bd62-422b-8e98-e32e717db0e2] (Running)
	 Daemon Thread [Start Level: Equinox Container: 2ac4cdd7-bd62-422b-8e98-e32e717db0e2] (Running)	
 Daemon Thread [Refresh Thread: Equinox Container: 2ac4cdd7-bd62-422b-8e98-e32e717db0e2] (Running)	
 Daemon Thread [Bundle File Closer] (Running)	
 Daemon Thread [SCR Component Actor] (Running)	 
Thread [Gogo shell] (Running)
	 Thread [app thread - org.eclipse.fx.ui.workbench.fx.application.0] (Running)	 Thread [JavaFX-Launcher] (Running)	
 Daemon Thread [QuantumRenderer-0] 
(Running)	
 Daemon Thread [InvokeLaterDispatcher] (Running)	
 Thread [JavaFX Application Thread]
  (Suspended)	
 DefaultJFXApp.setProductApplicationName
(                             ) line: 
      85 DefaultJFXApp.<init>(E4Application) line: 
       54 DefaultJFXApp.<init>
(                ) line: 
  39	 NativeConstructorAccessorImpl.newInstance0(Constructor<?>, Object[ 
                                         ]) line: not available [native method]	 NativeConstructorAccessorImpl.newInstance(Object[]) line: 
62	 DelegatingConstructorAccessorImpl.newInstance(Object[]) line
45	 Constructor<T>.newInstance(Object...) line: 
490	 LauncherImpl.lambda$launchApplication
1$8(Class, AtomicReference, String[]) line: 
802	 4de.my.rcp.product [Eclipse Application]	 org.eclipse.equinox.launcher.Main at localhost:
65485	 Thread   [       main        
                   ] (Running)	 Thread [Active Thread: Equinox Container: 2ac4cdd7-bd62-422b-8e98-e32e717db0e2]        
(Running)	 Daemon Thread 
[Framework Event Dispatcher: Equinox Container
: 2ac4cdd7-bd62-422b-8e98-e32e717db0e2] (Running)	
 Daemon Thread [Start Level: Equinox Container:
 2ac4cdd7-bd62-422b-8e98-e32e717db0e2] (Running)
	 Daemon Thread [Refresh Thread: Equinox Container: 
2ac4cdd7-bd62-422b-8e98-e32e717db0e2] (Running)	
 Daemon Thread [Bundle File Closer] (Running)	
 Daemon Thread
 [SCR Component Actor] (Running)	 
Thread [Gogo shell] (Running)
	 Thread [app thread - org.eclipse.fx.ui.workbench.fx.application.0] (Running)	
 Thread [JavaFX-Launcher] (Running)	
 Daemon Thread [QuantumRenderer-0] (Running)	 Daemon Thread [InvokeLaterDispatcher] (Running)	 
Thread [JavaFX Application Thread] (Suspended)	 DefaultJFXApp.setProductApplicationName() line: 
85	 DefaultJFXApp.<init>        (E4Application) line:
 54	 DefaultJFXApp.<init>(                                                          ) line:
 39	 NativeConstructorAccessorImpl.newInstance
0(
Constructo
r<?>, Object    [                            ]) line: not available [native method]	 NativeConstructorAccessorImpl.newInstance(Object   [               ]) line: 
62	 DelegatingConstructorAccessorImpl.newInstance(Object[]) line: 
45	 Constructor<T>.newInstance(            Object         ) line:
 490	 LauncherImpl.lambda$launchApplication
1$8      (Class, AtomicReference, String  [                      
                               ]    ) line: 
802	
 49162038.run(                            ) line: not available	 PlatformImpl.lambda$runAndWait
$12        (Runnable, CountDownLatch) line:
 455	
 468381491.run(                   ) line: not available	 PlatformImpl.lambda$runLater
$10        (Runnable) line:
 428	  
1031499101.run(                 ) line: not available	 AccessController.doPrivileged(PrivilegedAction
<T>, AccessControlContext) line: not available                                     [native method]	 PlatformImpl.lambda$runLate 
$11(Runnable, AccessControlContext      
          ) line:
 427	
 401110568.run(                          ) line: not available	 InvokeLaterDispatcher
$Future.run(                                       ) line: 
96	 WinApplication._runLoop(Runnable) line: not available [native method]	 WinApplication.lambda$runLoop
$3                      (int, Runnable)line
: 174	 1032320556.run(                   ) line: not available	 Thread.run() line: 834	 Daemon Thread                                [Thread-4] (Running)	 ###\openjdk
11.0.2\bin\javaw.exe                        
             (
23.06.2
     020, 
18:00:      
 de.my.rcp.product [Eclipse Application                              ]	 org.eclipse.equinox.launcher.Main at localhost:
65485	              Thread [main] (Running)	 Thread [Active Thread: Equinox Container:
 2ac4cdd7-bd62-422b-8e98-e32e717db0e2] (Running)	
 Daemon Thread                  [Framework Event Dispatcher: Equinox Container
: 2ac4cdd7-bd62-422b-8e98-e32e717db0e2         
] (Running)	       Daemon Thread [Start Level: Equinox Container: 2ac4cdd7-bd62-422b-8e98-e32e717db0e2] (Running)	
 Daemon Thread [Refresh Thread: Equinox Container: 2ac4cdd7-bd62-422b-8e98-e32e717db0e2] (Running)	
 Daemon Thread [Bundle File Closer] (Running)	
 Daemon Thread [SCR Component Actor] (Running)	 
Thread [Gogo shell] (Running)	
 Thread [app thread - org.eclipse.fx.ui.workbench.fx.application.0] (Running)	
 Thread [JavaFX-Launcher] (Running)
	 Daemon Thread [QuantumRenderer-0] (Running)	 Daemon Thread [InvokeLaterDispatcher] (Running)	
 Thread [JavaFX Application Thread]                                (Suspended)	 DefaultJFXApp.setProductApplicationName() line: 
85	 DefaultJFXApp
.<init>      (E4Application) line:
 54	 DefaultJFXApp.
<init>(                                                             ) lin
: 39	 NativeConstructorAccessorImpl.newInstance
     0(    Constructor<?>, Object[                       ]) line: not available [native method]	 
NativeConstructorAccessorImpl.newInstance
(Object
   [                   
    ]) line:
 62	 
DelegatingConstructorAccessorImpl.newInstance(Object[        ]) l
ine: 45	 Constructor
<T>.newInstance     
                                                (Objec t.) line: 
490	 LauncherImpl.lambda
$launchApplication 
1$8(Class, AtomicReference, String[                        ]  ) line:
 802	 
49162038.run(                         ) line: not available	 PlatformImpl.lambda$runAndWait
$12(Runnable, CountDownLatch) line: 
455	
 468381491.run(                ) line: not available	 PlatformImpl.lambda$runLater
$10(Runnable) line: 
428	 
1031499101.run(                                          ) line: not available	 AccessController.doPrivileged(PrivilegedAction
<T>, AccessControlContext)       line: not available 
[native method]	 
PlatformImpl.lambda$runLater
$11(Runnable, AccessControlContext) line: 
427	 
401110568.run(                                        ) line: not available	 InvokeLaterDispatcher$Future.run() line: 
96	 WinApplication._runLoop(Runnable) line: not available
 [native method]	 WinApplication.lambda$runLoop$3(int, Runnable) line: 174	 1032320556.run() line: not available
	 Thread.run() line: 834	 Daemon Thread [Thread-4] (Running)	 ###\openjdk-11.0.2\bin\javaw.exe (23.06.2020, 18:00:16  169162
038.run(                      ) line: not available	 PlatformImpl.lambda$runAndWait
$12(Runnable, CountDownLatch) line: 
455	::468381491       .run(                        ) line: not available	 PlatformImpl.lambda$runLater$10
(Runnable) line: 428	
 1031499101.run(                       ) line: not available	 AccessController.doPrivileged(PrivilegedAction<T>, AccessControlContext) line: not available [native method]	 PlatformImpl.lambda$runLater$11(Runnable, AccessControlContext) line: 427	 401110568.run() line: not available	 InvokeLaterDispatcher$Future.run() line: 96	 WinApplication._runLoop(Runnable) line: not available [native method]	 WinApplication.lambda$runLoop$3(int, Runnable) line: 174	 1032320556.run() line: not available	 Thread.run() line: 834	 Daemon Thread [Thread-4] (Running)	 ###\openjdk-
11.0.2\bin\javaw.exe (23.06.2020, 18:00:16

**Pull request closed without merging**
